export const ADDTO_CART_SUCCESS = "ADDTO_CART_SUCCESS";

export const QUANTITY_INCREASE = "QUANTITY_INCREASE";
export const QUANTITY_DECREASE = "QUANTITY_DECREASE";

export const DELETE_FROM_CART = "DELETE_FROM_CART";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const CREATE_PRODUCT_PENDING = "CREATE_PRODUCT_PENDING";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";

export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS" 
